// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import static mdb.Main.isScript;
import static mdb.Main.userInput2;
import Jakarta.util.*;

import java.io.*;
import java.util.*;

public class ScriptCmd extends Script {

    final public static int ARG_LENGTH = 1 /* Kludge! */ ;
    final public static int TOK_LENGTH = 3 ;

    public void execute () {
    	String filename = getSTRING_LITERAL().getTokenName();
 	   	filename = filename.substring(1,filename.length()-1);
 	   	isScript = true;
		
 	   	try {
 	   	    
 	   	   userInput2 = new BufferedReader(new FileReader("/"+filename));
		

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
 	   
    }

    public AstToken getSCRIPT () {
        
        return (AstToken) tok [0] ;
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [2] ;
    }

    public AstToken getSTRING_LITERAL () {
        
        return (AstToken) tok [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, true, true} ;
    }

    public ScriptCmd setParms (AstToken tok0, AstToken tok1, AstToken tok2) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* SCRIPT */
        tok [1] = tok1 ;            /* STRING_LITERAL */
        tok [2] = tok2 ;            /* SEMI */
        
        InitChildren () ;
        return (ScriptCmd) this ;
    }

}
